#!/usr/local/bin/python

import argparse
import random
import string


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-b', '--base', type=str, default='mcadiz.truecar', help='Base of email address')
    parser.add_argument('-d', '--domain', type=str, default='gmail.com', help='Domain of email address')
    args = parser.parse_args()

    corpus = string.ascii_letters + string.digits

    kwargs = {
        'base': args.base,
        'random': ''.join([random.choice(corpus) for _ in range(16)]),
        'domain': args.domain,
    }

    print '{base}+{random}@{domain}'.format(**kwargs)
