#!/usr/bin/perl -w

use strict;
use JSON;
use Data::Dumper;

my $json = JSON->new->allow_nonref;

if (@ARGV) {
    for my $file (@ARGV) {
        if (-f $file) {
            open(local *FH, "<$file") or die;
            my $input = do { local $/; <FH> };
            close(FH);
            print Dumper(decode($input));
        }
    }
}
elsif (! -t STDIN) {
    my @input = ();
    while (<>) {
        push @input, $_;
    }
    my $input = join '', @input;
    print Dumper(decode($input));
}

sub decode
{
    my $input = shift;
    return $json->decode($input) if $input;
}
