#!/bin/bash

function usage
{
    echo "$0 <hotfix_branch> <release tag>"
}

function checkgit
{
    if [[ -z `which git` ]]; then
        echo "git not on PATH, bailing"
        exit 1
    fi
}

function checkargs
{
    if [[ $# -ne 2 ]]; then
        usage
        exit 2
    fi

    HOTFIX_BRANCH=$1
    RELEASE_TAG=$2

    FOUND_BRANCH=`git branch -a | grep $HOTFIX_BRANCH | tr -d ' ' | tr -d '\*'`
    FOUND_TAG=`git tag | grep $RELEASE_TAG | tr -d ' '`

    if [[ -n $FOUND_BRANCH ]]; then
        echo "Branch \`$FOUND_BRANCH' already exists, bailing"
        exit 3
    fi

    if [[ -z $FOUND_TAG ]]; then
        echo "Tag \`$RELEASE_TAG' doesn't exist, bailing"
        exit 4
    fi
}

function mkhotfix
{
    checkgit
    checkargs $*

    HOTFIX_BRANCH=$1
    RELEASE_TAG=$2

    git checkout -b $HOTFIX_BRANCH $RELEASE_TAG

    if [[ $? -ne 0 ]]; then
        echo "Error: couldn't make branch $HOTFIX_BRANCH"
    fi
}

mkhotfix $*
