#!/usr/bin/env python

import string
import random

alphanumeric = string.lowercase + string.digits


if __name__ == '__main__':
    res = []
    for i in [8, 4, 4, 4, 12]:
        res.append(''.join([random.choice(alphanumeric) for _ in range(i)]))
    print '-'.join(res)
