#!/bin/bash

#
# Tue Nov 29 18:09:58 PST 2016
# tweaked version http://dev-tricks.net/automating-gnu-screen-startup
#

SCREEN_SESSION="SCREEN - `date`"
SCREENS="l00k l00k server manage log console client"
NUM=0

# start in daemon mode
screen -dmS "$SCREEN_SESSION"

for SCREEN_NAME in $(echo "${SCREENS}" ); do
    # create new window
    screen -S "${SCREEN_SESSION}" -p {$NUM} -X screen
    # name new window
    screen -S "${SCREEN_SESSION}" -p ${NUM} -X title ${SCREEN_NAME}
    # fix backspace/delete
    screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'. ~/bin/stty-keys\r'
    case "${NUM}" in
        "0")
            echo ${SCREEN_NAME}
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/vipr-ui/\r'
            ;;
        "1")
            echo ${SCREEN_NAME}
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/vipr-ui/\r'
            ;;
        "2")
            echo ${SCREEN_NAME}
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/vipr-ui/\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'gluestick start\r'
            ;;
        "3")
            echo ${SCREEN_NAME}
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/vipr-ui/\r'
            ;;
        "4")
            echo ${SCREEN_NAME}
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/vipr-ui/\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'tail -f server.log\r'
            ;;
        "5")
            echo ${SCREEN_NAME}
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/js-playground/\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'npx babel-node\r'
            ;;
        "6")
            echo ${SCREEN_NAME}
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/vipr-ui/\r'
            ;;
        *)
            echo "Bad screen ${NUM}?"
            ;;
    esac
    NUM=$((NUM + 1))
done

# kill initial window (i.e. only keep explicitly created)
screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'exit\r'
echo "Now joining screen session ${SCREEN_SESSION}"
screen -x "${SCREEN_SESSION}"
