#!/bin/bash

#
# Thu Jan 23 09:09:28 PST 2014
# tweaked version http://dev-tricks.net/automating-gnu-screen-startup
#

SCREEN_SESSION="SCREEN - `date`"
SCREENS="l00k l00k runserver manage log db ucr l00k ws ws"
NUM=0

# start in daemon mode
screen -dmS "$SCREEN_SESSION"

for SCREEN_NAME in $(echo "${SCREENS}" ); do
    # create new window
    screen -S "${SCREEN_SESSION}" -p {$NUM} -X screen
    # name new window
    screen -S "${SCREEN_SESSION}" -p ${NUM} -X title ${SCREEN_NAME}
    # fix backspace/delete
    screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'. ~/bin/stty-keys\r'
    case "${NUM}" in
        "0" | "1")
            echo "l0st"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/trunk.git/\r'
            ;;
        "2")
            echo "vagrant up"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/boxes/centos64-fcs-machine2\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'vagrant up && ssh `cat ifeth1`\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'. ~/bin/memcached-start.sh\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd /usr/local/fonality\r'
            ;;
        "5")
            echo "fcs"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'ssh devbox5.lotsofclouds.fonality.com\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/sql/mysql.git\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'mysql -u fonality -h dev-db.lotsofclouds.fonality.com fcs\r'
            ;;
        "3" | "4" | "6" | "7")
            echo "ssh ifeth1"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/boxes/centos64-fcs-machine2/\r'
            if [[ "$1" = "now" ]]; then
                screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'ssh `cat ifeth1`\r'
            else
                screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'sleep 99 && ssh `cat ifeth1`\r'
            fi
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd /usr/local/fonality\r'
            ;;
        "8" | "9" | "10")
            echo "ssh devbox5"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'ssh devbox5.lotsofclouds.fonality.com\r'
            ;;
        *)
            echo "Bad screen ${NUM}?"
            ;;
    esac
    NUM=$((NUM + 1))
done

# kill initial window (i.e. only keep explicitly created)
screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'exit\r'

echo "Now join screen session ${SCREEN_SESSION}"
