#!/bin/bash

#
# Thu Jan 23 09:09:28 PST 2014
# tweaked version http://dev-tricks.net/automating-gnu-screen-startup
#

SCREEN_SESSION="SCREEN - `date`"
SCREENS="l00k l00k runserver manage log db ucr ucr used used used"
NUM=0

# start in daemon mode
screen -dmS "$SCREEN_SESSION"

for SCREEN_NAME in $(echo "${SCREENS}" ); do
    # create new window
    screen -S "${SCREEN_SESSION}" -p {$NUM} -X screen
    # name new window
    screen -S "${SCREEN_SESSION}" -p ${NUM} -X title ${SCREEN_NAME}
    # fix backspace/delete
    screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'. ~/bin/stty-keys\r'
    case "${NUM}" in
        "0")
            echo "l00k"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'workon tcdc\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/tcdc-main/\r'
            ;;
        "1")
            echo "l00k"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'workon tcdc\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/tcdc-main/\r'
            ;;
        "2")
            echo "runserver"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'workon tcdc\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/tcdc-main/\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'python bin/runserver.py\r'
            ;;
        "3")
            echo "manage"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'workon tcdc\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/tcdc-main/tcdc\r'
            ;;
        "4")
            echo "log"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd /opt/truecar/var/log/\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'tail -f tcdc.log\r'
            ;;
        "5")
            echo "db"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'mkws\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cdws\r'
            ;;
        "6")
            echo "ucr"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'workon ucr\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/dealer-portal/ucr/\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'python bin/runserver.py\r'
            ;;
        "7")
            echo "ucr"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'workon ucr\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/dealer-portal/ucr/\r'
            ;;
        "8")
            echo "used"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'workon used\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/used-car/\r'
            ;;
        "9")
            echo "used"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'workon used\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/used-car/\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'python bin/runserver.py\r'
            ;;
        "10")
            echo "npm"
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'workon used\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'cd ~/workspace/src/used-car/used/frontend\r'
            screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'npm install && npm start\r'
            ;;
        *)
            echo "Bad screen ${NUM}?"
            ;;
    esac
    NUM=$((NUM + 1))
done

# kill initial window (i.e. only keep explicitly created)
screen -S "${SCREEN_SESSION}" -p ${NUM} -X stuff $'exit\r'

echo "Now join screen session ${SCREEN_SESSION}"
