#!/bin/bash

SSH_AGENT=`ssh-add -l 2>&1 | grep 'not open'`
if [[ -n "$SSH_AGENT" ]]; then
    echo "Error: ssh-agent not started"
    exit 1
fi

OS=`uname`
if [[ "$OS" = "Darwin" ]]; then
    LIBAETPKSS='/usr/local/lib/libaetpkss.dylib'
elif [[ "$OS" = "Linux" ]]; then
    LIBAETPKSS='/usr/lib/libaetpkss.so'
fi

AETPKSS=`ssh-add -l | grep $LIBAETPKSS | awk '{print $3}'`
if [ -z "$AETPKSS" ]; then
    ssh-add -s $LIBAETPKSS
fi

echo && ssh-add -l
