#!/bin/bash

#BOX_DIR=${HOME}/workspace/boxes

if [[ -z "" ]]; then
    echo "envvar BOX_DIR undefined, bailing"
    exit 1
fi

VM_LIST=`find $BOX_DIR -name 'Vagrantfile'`

for file in $(echo $VM_LIST ); do
    VM=`dirname $file`
    echo "Shutting down $VM"
    cd $VM && vagrant halt
done
